name: Generate Directory Listing

# This workflow runs every time you push a change to your main branch
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job generates the directory listing
  generate-listing:
    runs-on: ubuntu-latest
    steps:
      # First, this step checks out a copy of your repository so the workflow can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # This is the key step. It uses a community action to create the index.html file.
      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          # FOLDER specifies which directory to create the index for.
          # Use '.' for the root directory of your repository.
          FOLDER: .

      # This step takes the newly created index.html and prepares it for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Upload the entire directory

  # This job deploys the generated files to GitHub Pages
  deploy:
    # It needs the 'generate-listing' job to complete successfully first
    needs: generate-listing
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # This is the final step that deploys your files to your GitHub Pages site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
